spring:
  datasource:
    url: jdbc:postgresql://<PROD_DB_HOST>:5432/<PROD_DB_NAME>
    driver-class-name: org.postgresql.Driver
    username: <PROD_DB_USER>
    password: <PROD_DB_PASSWORD>
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  sql:
    init:
      mode: never
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations:
      - classpath:db/migration/common
      - classpath:db/migration/postgresql
