version: "3.8"

services:
  redis:
    image: redis:7.4.8-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - microservices-network
    restart: always

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: micro_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - microservices-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - microservices-network
    restart: always

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_URI=http://service-discovery:8761/eureka/
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - DB_URL=jdbc:postgresql://postgres:5432/micro_db
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - JWT_SECRET=this-is-a-very-secure-key-and-is-longer-than-32-characters
      - JWT_EXPIRATION=3600000
    depends_on:
      - service-discovery
      - redis
      - rabbitmq
      - postgres
    networks:
      - microservices-network

  board-service:
    build: ./board-service
    container_name: board-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_URI=http://service-discovery:8761/eureka/
      - REDIS_HOST=redis
      - DB_URL=jdbc:postgresql://postgres:5432/micro_db
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - JWT_SECRET=this-is-a-very-secure-key-and-is-longer-than-32-characters
    depends_on:
      - service-discovery
      - postgres
    networks:
      - microservices-network

  tenant-provisioning-worker:
    build: ./tenant-provisioning-worker
    container_name: tenant-provisioning-worker
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_URI=http://service-discovery:8761/eureka/
      - RABBITMQ_HOST=rabbitmq
      - DB_URL=jdbc:postgresql://postgres:5432/micro_db
      - DB_USERNAME=user
      - DB_PASSWORD=password
    depends_on:
      - service-discovery
      - rabbitmq
      - postgres
    networks:
      - microservices-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_URI=http://service-discovery:8761/eureka/
      - REDIS_HOST=redis
      - JWT_SECRET=this-is-a-very-secure-key-and-is-longer-than-32-characters
      - JWT_EXPIRATION=3600000
    depends_on:
      - service-discovery
      - auth-service
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  postgres_data:
