spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: auth-service
        uri: lb://auth-service
        predicates:
          - Path=/auth/**
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1
          min-idle: 0

jwt:
  secret: lFMCnn04hFUty4RnSNjDDfQ8eYBySWTWis5AmbGiv6U=
  access-token-expire-time: 3600
  refresh-token-expire-time: 604800
  secret-key-algorithm: HS256

frontend:
  url: http://localhost:3000
  login-url: /login
  logout-url: /logout