spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
      - id: auth-service
        uri: lb://auth-service
        predicates:
          - Path=/auth/**, /user/**, /secure/**, /role/**, /tenant/**
      - id: board-service
        uri: lb://board-service
        predicates:
          - Path=/board/**
        # filters:
        #   - JwtAuthentication
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1
          min-idle: 0

server:
  port: 8070

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: override-from-config-server
  access-token-expire-time: 3600000
  refresh-token-expire-time: 604800000
  secret-key-algorithm: HS256

# 보호가 필요한 API 경로 설정
# protected-paths:
#   - /user/**
#   - /admin/**
#   - /api/secure/**
#   - /internal/**

frontend:
  url: http://localhost:3000
  login-path: /auth/login