spring:
  application:
    name: service-discovery
  profiles:
    active: local

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false # Disable registration with Eureka server
    fetch-registry: false # Disable fetching the registry from Eureka server
  server:
    wait-time-in-ms-when-sync-empty: 0 # 초기 sync 대기 시간 최소화 (옵션)
