ALTER TABLE tenant ALTER COLUMN id RESTART WITH (SELECT COALESCE(MAX(id), 0) + 1 FROM tenant);
ALTER TABLE appuser ALTER COLUMN id RESTART WITH (SELECT COALESCE(MAX(id), 0) + 1 FROM appuser);
ALTER TABLE oauth_account ALTER COLUMN id RESTART WITH (SELECT COALESCE(MAX(id), 0) + 1 FROM oauth_account);
ALTER TABLE roles ALTER COLUMN id RESTART WITH (SELECT COALESCE(MAX(id), 0) + 1 FROM roles);
ALTER TABLE appuser_roles ALTER COLUMN id RESTART WITH (SELECT COALESCE(MAX(id), 0) + 1 FROM appuser_roles);
ALTER TABLE modules ALTER COLUMN id RESTART WITH (SELECT COALESCE(MAX(id), 0) + 1 FROM modules);
ALTER TABLE tenant_modules ALTER COLUMN id RESTART WITH (SELECT COALESCE(MAX(id), 0) + 1 FROM tenant_modules);
ALTER TABLE user_modules ALTER COLUMN id RESTART WITH (SELECT COALESCE(MAX(id), 0) + 1 FROM user_modules);
