plugins {
    id 'java'
}

group = 'com.microservices'
version = '1.0.0'

java {
    sourceCompatibility = '17'
}

compileJava {
    options.encoding = 'UTF-8'
}

compileTestJava {
    options.encoding = 'UTF-8'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.14.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation 'org.projectlombok:lombok:1.18.36'
    annotationProcessor 'org.projectlombok:lombok:1.18.36'
}

jar {
    enabled = true
    archiveClassifier = ''
}

test {
    useJUnitPlatform()
}
