plugins {
    id 'java'
}

group = 'com.microservices'
version = '1.0.0'

java {
    sourceCompatibility = '17'
}

compileJava {
    options.encoding = 'UTF-8'
}

compileTestJava {
    options.encoding = 'UTF-8'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.14.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
    testRuntimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    testRuntimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

    compileOnly 'org.springframework:spring-webflux:6.1.0'
    compileOnly 'org.springframework:spring-web:6.1.0'
    compileOnly 'org.springframework.security:spring-security-core:6.2.0'
    compileOnly 'org.springframework.security:spring-security-web:6.2.0'
    compileOnly 'jakarta.servlet:jakarta.servlet-api:6.0.0'
    compileOnly 'io.projectreactor:reactor-core:3.6.0'

    implementation 'org.slf4j:slf4j-api:2.0.16'

    implementation 'org.projectlombok:lombok:1.18.36'
    annotationProcessor 'org.projectlombok:lombok:1.18.36'
}

jar {
    enabled = true
    archiveClassifier = ''
}

test {
    useJUnitPlatform()
}
